# Generated by Django 4.2.18 on 2025-02-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=70, null=True)),
                ('data_inicial', models.DateField(null=True)),
                ('data_final', models.DateField(null=True)),
            ],
        ),
    ]
