# Generated by Django 4.2.18 on 2025-02-18 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0002_remove_instrutores_codigo_and_more'),
        ('alunos', '0001_initial'),
        ('tipodeatividade', '0002_alter_tipodeatividade_descricao'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ausencia', models.DateField(default=datetime.datetime(2025, 2, 18, 0, 2, 23, 422860, tzinfo=datetime.timezone.utc), help_text='Data da falta do aluno na turma')),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno da turma', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Informe a turma do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora em que a hora da aula da Turma')),
                ('duracao_aula', models.SmallIntegerField(default=30, help_text='Informe a duração da aula da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 2, 18, 0, 2, 23, 422860, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(blank=True, help_text='Informe a data final da Turma', null=True)),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('id_instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutores')),
                ('matricula_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TurmaAlunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', models.DateField(default=datetime.datetime(2025, 2, 18, 0, 2, 23, 422860, tzinfo=datetime.timezone.utc), help_text='Data da matrícula do aluno na turma')),
                ('data_fim_matricula', models.DateField(blank=True, help_text='Data de fim de matrícula do aluno na turma', null=True)),
                ('matricula_aluno', models.ForeignKey(help_text='Matrícula do aluno da turma', on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('numero_turma', models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
        ),
        migrations.DeleteModel(
            name='Turmas',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='numero_turma',
            field=models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
    ]
