# Generated by Django 4.2.18 on 2025-02-19 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('tipodeatividade', '0002_alter_tipodeatividade_descricao'),
        ('instrutores', '0002_remove_instrutores_codigo_and_more'),
        ('turmas', '0002_ausencia_turma_turmaalunos_delete_turmas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='data_ausencia',
            field=models.DateField(default=datetime.datetime(2025, 2, 19, 23, 59, 0, 426796, tzinfo=datetime.timezone.utc), help_text='Data da falta do aluno na turma'),
        ),
        migrations.AlterField(
            model_name='turmaalunos',
            name='data_inicio_matricula',
            field=models.DateField(default=datetime.datetime(2025, 2, 19, 23, 59, 0, 426796, tzinfo=datetime.timezone.utc), help_text='Data da matrícula do aluno na turma'),
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('numero', models.AutoField(help_text='Informe a turma do Aluno', primary_key=True, serialize=False)),
                ('horario_aula', models.TimeField(help_text='Informe a hora em que a hora da aula da Turma')),
                ('duracao_aula', models.SmallIntegerField(default=30, help_text='Informe a duração da aula da Turma')),
                ('data_inicial', models.DateField(default=datetime.datetime(2025, 2, 19, 23, 59, 0, 426796, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma')),
                ('data_final', models.DateField(blank=True, help_text='Informe a data final da Turma', null=True)),
                ('codigo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodeatividade.tipodeatividade')),
                ('id_instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutores')),
                ('matricula_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.alunos')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='numero_turma',
            field=models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas'),
        ),
        migrations.AlterField(
            model_name='turmaalunos',
            name='numero_turma',
            field=models.ForeignKey(help_text='Número da turma do aluno.', on_delete=django.db.models.deletion.CASCADE, to='turmas.turmas'),
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
