# Generated by Django 5.1.6 on 2025-02-26 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_alter_ausencia_data_ausencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='data_ausencia',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 36, 40, 197542, tzinfo=datetime.timezone.utc), help_text='Data da falta do aluno na turma'),
        ),
        migrations.AlterField(
            model_name='turmaalunos',
            name='data_inicio_matricula',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 36, 40, 197542, tzinfo=datetime.timezone.utc), help_text='Data da matrícula do aluno na turma'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 2, 26, 15, 36, 40, 197542, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da Turma'),
        ),
    ]
