# Generated by Django 4.2.18 on 2025-02-26 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_alter_ausencia_data_ausencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='data_ausencia',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data da falta do aluno na turma'),
        ),
        migrations.AlterField(
            model_name='turmaalunos',
            name='data_inicio_matricula',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data da matrícula do aluno na turma'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='data_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='Informe a data inicial da Turma'),
        ),
    ]
